language: scala
scala: 2.12.8
jdk: openjdk12
script:
  - sbt ++$TRAVIS_SCALA_VERSION "
    ;sbt:scalafmt::test
    ;sl-tester/scalafmt::test
    ;sl-tester/test:scalafmt::test
    ;sl-tester/test"
notifications:
  email: false
  slack:
    secure: CsOm8b77Fh3ob9Rc2wDFzsXT6yB5ajN1vADKz2yna70Hk4DjtMkpY/wDvnFcOlWIOPvljaKkpYzKShj3RxBT9uLZ/TEALZ0mepjIzc2sL0WWcxHJVXchV7hvyjsQi5Y0OlSjR4UTigWquSTqt9UDiokMAAxVxTco11gfIZBfGJ0hrOm/Qta3wnNzkw0tWa+A5J9dArLOtPmnmdRTPT5/uOaoTZB5rZ9+JrEiafOhZiKWMhaHhtWCNUVtOWKcGyfi/ZOj69WpyBMQ8mfnwYPI0W0SY3tD9g4bXmyyCvCqvHS3jFx6O8jm+iPKticEClIp+QxkVOjqx7KZoaI34wk1FehdN9/yBzioN+gDwTVR01E6drJB8tLyp7MsknSOvYL+7XtVwudeD5gjxXEZc95ne/5COlrl1OGOQ7h2SmW9L/n51xasLqMHzPG6iPL1+kenfOAU8Ac3TPvDbjFwipFDjPYpk4N3Im4R8BAt6Q6s6q/rGr+ubTTCO/EtC7xozMJlSBFK+sXSX7NXviKt4u0miWCMqqGL/1kRCWgbtXwZHk+Kh2o4ej0TQuR28Q1PhIGSI3LNoxZklsvyo7uENknN4rpw0Tq59TBU/GkCw+7cq/5zoE7tOFXuyvzP4QTzA6y85WBJMng4JLU0bC17dD4jzKlHl4rIGvtqhmrRLFz5bbU=
