version: "3.7"

services:

  db:
    image: mysql:8
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: serious-lunch
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306

  flyway:
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:mysql://localhost:3306/serious_lunch_development -schemas=myschema -user=root -password=serious-lunch -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db

volumes:
  mysql:
