version: "3.7"

services:

  db:
    image: mysql:8
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql:
